### ISSUE TITLE
Question/request about promoter bed

### ISSUE THREAD

**Issue by drc111** [csoneson/NativeRNAseqComplexTranscriptome#1]
Hi @csoneson,

I have a question about the universal promoter bed file that was created for your FLAIR analysis: was it created by merging **all** records from the 9 cell lines in the Broad ChromHMM UCSC track, or by merging overlapping or non-overlapping promoter coordinates between these cell lines?

If possible, could you please make the promoter bed file used at the FLAIR-collapse step available here?

Best,
Sebastian

**Comment by csoneson** [comment]
Hi Sebastian, 

I have added the bed file to the repo. 
See https://github.com/csoneson/NativeRNAseqComplexTranscriptome/blob/master/Rscripts/merge_promoter_bed_files.R for the code used to generate this file.

**Comment by drc111** [comment]
Thank you very much!
